#!/bin/zsh


if [ ! "$SSH_CONNECTION" -a $(id -u) -ne 0 ] ; then # don't open on ssh connection, and when user is root.

# Music
## Playback
    amixer -- sset  Master   100% unmute
    amixer -- sset  PCM      100% unmute
    amixer -- sset  Speaker       unmute
    amixer -- sset  Beep     100% unmute

## Capture
    amixer -- sset 'Front Mic Boost' 0%
    amixer -- sset 'Mic Boost'       0%

## Do not know
    amixer -- sset 'Caller ID'   mute
    amixer -- sset 'Off-hook'    mute


    if ! pgrep remind  >& /dev/null ; then
    # remind -z1 \
    #     -k"~/bin/popremind %s &" \
    #     ${DOTREMINDERS-~/.Organize/remind/Reminders/init.rem} &!

        remind -z1 \
            -k~/bin/popremind\ %s\ \& \
            ${DOTREMINDERS-~/.Organize/remind/Reminders/init.rem} &!

    # for testing remind that do not go into daemon mode, try below command
    # remind -aqh -k"~/bin/popremind %s &" ${DOTREMINDERS-~/.Organize/remind/Reminders/init.rem}

    fi

    foreach server (general) {
        if [ ! -e ~/.emacs.d/server/${server} ] ||
       	    ! { # bundler command is not here for timeout it only for zsh
                # timeout 7 command emacsclient -f ~/.emacs.d/server/${server}  -e '(message "works")';
                # timeout 10 command emacsclient -f ~/.emacs.d/server/${server}  -e '(message "works")'

                # do notr delete: timeout [ TIMEOUT ] don't recognize command `command', it is only for zsh
                timeout 7 emacsclient -f ~/.emacs.d/server/${server}  -e '(message "works")';
                timeout 10 emacsclient -f ~/.emacs.d/server/${server}  -e '(message "works")'
            } ; then
            # blow one is not allow gnus to read its ~/.gnus file automatically.
	    rm -f   \#.ido.last\#
            pkill emacs ; EMACS_SERVER_NAME=$server command emacs --daemon=$server
        else
            command emacsclient -n -f ~/.emacs.d/server/${server}  -e '(plan)';
        fi
    }

    # foreach server (general) {
    #     if [ ! -e ~/.emacs.d/server/${server} ] ||
    #         # do notr delete: timeout [ TIMEOUT ] don't recognize command `command', it is only for zsh
    #    	    ! timeout 7 emacsclient -f ~/.emacs.d/server/${server}  -e '(message "works")'; then
    #         # blow one is not allow gnus to read its ~/.gnus file automatically.
    #         pkill emacs ; EMACS_SERVER_NAME=$server command emacs --daemon=$server
    #     fi
    # }

fi

whence leave &&
leave +0800


