#!/usr/bin/env zsh


if pgrep at-spi-registry >/dev/null 2>&1  # && [ -x /usr/libexec/at-spi-registryd ]
then
    pkill at-spi-registry
fi

# whence -p gnome-screensaver &&
# pgrep gnome-screensaver ||
# gnome-screensaver &!

if [ -x /usr/libexec/gnome-settings-daemon ] ; then
    pgrep gnome-settings && pkill gnome-settings
else
    whence -p gnome-settings-daemon &&
    pgrep gnome-settings && pkill gnome-settings-daemon
fi

pgrep nm-applet && pkill nm-applet



if pgrep gnome-keyring-d >& /dev/null ; then
    pkill gnome-keyring-d >& /dev/null
    pkill -9 gnome-keyring-d >& /dev/null
fi

foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    gnome-keyring-daemon
    gnome-power-manager
    mail-notification
    blueman-adapters
    blueman-applet
    bluetoothd
    pidgin
    synergys
    nm-applet
    ) {
        echo A DBUS >&2
        pgrep -l dbus-daemon >&2

        echo $prog
        if whence -p $prog &&
            pgrep $prog[0,15] ; then
            pkill $prog[0,15]
        fi

        echo B DBUS >&2
        pgrep -l dbus-daemon >&2

    }


if whence -p dbus-daemon >& /dev/null
then
    if pgrep dbus-daemon >& /dev/null
    then
        pkill dbus-daemon
    fi
fi

if whence -p xautolock >& /dev/null
then
    if pgrep xautolock >& /dev/null
    then
        pkill xautolock
    fi
fi

if whence -p keynav >& /dev/null  &&
       pgrep keynav >& /dev/null
then
    pkill keynav
fi

if whence -p autocutsel >& /dev/null
then
    if pgrep autocutsel >& /dev/null
    then
        pkill autocutsel
    fi
fi

if whence -p xcompmgr >& /dev/null
then
    if pgrep xcompmgr >& /dev/null
    then
        pkill xcompmgr
    fi
fi





[  -x ~/.rsetup/xlogout/run ] &&
~/.rsetup/xlogout/run

# Android LinConnect
if pgrep linconnect_serv >& /dev/null ; then
    pkill linconnect_serv
    sleep 1s;
    pkill -9 linconnect_serv
fi


if [ "x${HOST}" = "x" ]
then
    HOST=$HOSTNAME
fi
if [ "x${HOST}" != "x" ]
then
    __comp=wmlogout

    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        mkdir -p ~/.rsetup/${__comp}/run.d/
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi
