#!/usr/bin/env zsh


[ -x /usr/libexec/at-spi-registryd ] && pkill at-spi-registry

# whence -p gnome-screensaver &&
# pgrep gnome-screensaver ||
# gnome-screensaver &!

if [ -x /usr/libexec/gnome-settings-daemon ] ; then
    pgrep gnome-settings && pkill gnome-settings
else
    whence -p gnome-settings-daemon &&
    pgrep gnome-settings && pkill gnome-settings-daemon
fi

pgrep nm-applet && pkill nm-applet



if pgrep gnome-keyring-d >& /dev/null ; then
    pkill gnome-keyring-d >& /dev/null
    pkill -9 gnome-keyring-d >& /dev/null
fi

foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    gnome-keyring-daemon
    gnome-power-manager
    mail-notification
    blueman-adapters
    blueman-applet
    bluetoothd
    pidgin
    synergys
    nm-applet
    ) {
        echo A DBUS >&2
        pgrep -l dbus-daemon >&2

        echo $prog
        if whence -p $prog &&
            pgrep $prog[0,15] ; then
            pkill $prog[0,15]
        fi

        echo B DBUS >&2
        pgrep -l dbus-daemon >&2

    }


pkill dbus-daemon


[  -x ~/.rsetup/xlogout/run ] &&
~/.rsetup/xlogout/run

# Android LinConnect
if pgrep linconnect_serv >& /dev/null ; then
    pkill linconnect_serv
    sleep 1s;
    pkill -9 linconnect_serv
fi


__comp=wmlogout

if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
    if [ ! -d ~/.rsetup/${__comp}/env.d/${HOST} ] ; then
        rm -f ~/.rsetup/${__comp}/env.d/${HOST}
    fi
    mkdir ~/.rsetup/${__comp}/env.d/${HOST}
    cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
fi

[ -r ~/.rsetup/${__comp}/run.d/${HOST} ] && ~/.rsetup/${__comp}/run.d/${HOST}

unset __comp
