
* STARTED Org Context Clock
  DEADLINE: <2019-07-12 Fri> SCHEDULED: <2019-07-10 Wed>
  :PROPERTIES:
  :root:     /home/s/hell/.xemacs/elpa/pkgs/occ
  :Effort:   3h
  :END:
  :LOGBOOK:
  - Note taken on [2019-07-10 Wed 23:23] \\
    clocking out to clockin to <STARTED Deep interaction for non to unnamed, unnammed to named, named to named etc>
  - Note taken on [2019-07-10 Wed 22:37] \\
    Changed to buffer occ-obj-method.el from todo.org
  - Note taken on [2019-07-10 Wed 22:35] \\
    Changed to buffer *scratch* from *Messages*
  - Note taken on [2019-07-10 Wed 21:33] \\
    Changed to buffer occ-obj-method.el from occ-util-common.el
  CLOCK: [2019-07-10 Wed 21:32]--[2019-07-10 Wed 23:23] =>  1:51
  - Note taken on [2019-07-10 Wed 21:31] \\
    clocking in to here from last clock <Unnamed task 996>
  :END:
** Bugs
*** Helm goes into state where no key are defined so here is not way to come out excelt sending signal SIGUSR2

  I had noticed this happens when another read through minibuuffer command also triggered
  in below case it is "Save the LSDB mpw ?"

  #+begin_src log
  Sending via mail...
  Mark set
  nnimap read 0k from localhost
  Mark set [4 times]
  Sending...done
  Deleting article /home/s/hell/.emacs.d/.cache/autoconfig/gnus/News/drafts/drafts/2 in drafts...
  Delay header missing for article 1
  C-g is undefined [2 times]
  C-a is undefined
  C-g is undefined [7 times]
  M-x is undefined
  ESC is undefined [11 times]
  <up> is undefined [4 times]
  <down> is undefined [4 times]
  <next> is undefined [4 times]
  <switch-frame> is undefined [2 times]
  <up> is undefined
  <switch-frame> is undefined
  <up> is undefined
  <switch-frame> is undefined
  <up> is undefined
  C-g is undefined [14 times]
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  ESC is undefined
  <switch-frame> is undefined
  <down> is undefined [6 times]
  Entering debugger...
  <down> is undefined [6 times]
  C-g is undefined
  Entering debugger...
  Back to top level
  Delay header missing for article 1
  Save the LSDB now? (y or n) y
  The LSDB was saved successfully.

  #+end_src

** Todos



*** STARTED Deep interaction for non to unnamed, unnammed to named, named to named etc :DESIGN:
    :PROPERTIES:
    :Effort:   2h
    :END:
    :LOGBOOK:
    - Note taken on [2019-07-10 Wed 23:23] \\
      Changed to buffer occ-cl-utils.el from i.org.gpg
    CLOCK: [2019-07-10 Wed 23:23]--[2019-07-10 Wed 23:24] =>  0:01
    - Note taken on [2019-07-10 Wed 23:23] \\
      clocking in to here from last clock <Org Context Clock>
    :END:
*** NEXT Fast clocking/child clocking with property addition like fast property addition :DESIGN:USABILITY:
**** Fast property edit function for TSK
**** Fast property edit with try-clockin
*** caching ctxual-tsk or ctsk                                       :DESIGN:
 Here add support for per filter members
**** statistics addition                                             :DESIGN:
***** CLOSED Functions
      CLOSED: [2019-06-29 Sat 22:12]
      :LOGBOOK:
      - State "CLOSED"     from              [2019-06-29 Sat 22:12]
      :END:

***** Application
*** Rank Calculation                                                 :DESIGN:
**** Resolve TSK rank CTUAL_TSK rank issue                           :DESIGN:
**** Mutual relativity in property ranks MAX MIN etc                 :DESIGN:

*** NEXT Resolve clock occ integration                     :DESIGN:USABILITY:





*** TODO In editprop propagate property to childs also

*** Create manual unnamed/anonymous (different from automatic) child task mainly for FAST DISPATCH :USABILITY:
*** Create Single line task mainly for FAST DISPATCH              :USABILITY:
*** non tsk org entries                                              :DESIGN:





*** NEXT Rich menu with many class todo info note etc for capture
*** move filtering in helm selection.                             :USABILITY:
*** STARTED setup occ buffer with necessary hooks and cleanup etc   :TRIVIAL:
*** SCHEDULE and DEADLINE should only be enforced on non-repeatitive task. :USABILITY:
*** Addition of useful property methods                          :COMPLETION:
**** SubTree
**** timebeing
**** gitbranch
**** last clockout time
**** deadline
**** schedule
**** repetition




*** Try to use a org file itself for configurations e.g. kind of TODOs, mini max value in rank case etc.
*** See what org-pua annotation can help here.
*** Task categorys
**** Some task are todo now.
**** Some can need to be done in week, similarly fortnight, month
**** Some are in future, here schedule/deadline should not be asked
**** Some are in future but uncertain (they are to track.), here also schedule/deadline should not be asked





*** CLOSED Launcher
    CLOSED: [2019-06-29 Sat 22:07]
    :LOGBOOK:
    - State "CLOSED"     from              [2019-06-29 Sat 22:07]
    :END:

*** CLOSED creation of task in file node
    CLOSED: [2019-06-28 Fri 20:39]
    :LOGBOOK:
    - State "CLOSED"     from              [2019-06-28 Fri 20:39]
    :END:

*** CLOSED file list-tsk for list-tsk
    CLOSED: [2019-06-29 Sat 13:56]
    :LOGBOOK:
    - State "CLOSED"     from              [2019-06-29 Sat 13:56]
    :END:
*** CLOSED multi file tree-tsk on top
    CLOSED: [2019-06-29 Sat 00:06]
    :LOGBOOK:
    - State "CLOSED"     from              [2019-06-29 Sat 00:06]
    :END:
** Miscellaneous
*** Read https://github.com/roman/clocker.el
