(define-package "occ" "20190310.2156" "occ"
  '((org-plus-contrib "1")
    (dash "1")
    (lotus-utils "1")
    (org-clock-unnamed-task "1")
    (org-clock-resolve-advanced "1")
    (org-clock-hooks "1")
    (org-clock-wrapper "1")
    (org-capture+ "1")
    (switch-buffer-functions "1")))
