#!/bin/zsh

[ -x /usr/libexec/at-spi-registryd ] && DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/libexec/at-spi-registryd &!

# whence -p gnome-screensaver &&
# pgrep gnome-screensaver ||
# gnome-screensaver &!

if [ -x /usr/lib/gnome-settings-daemon/gnome-settings-daemon ] ; then
    pgrep gnome-settings || /usr/lib/gnome-settings-daemon/gnome-settings-daemon &!
elif [ -x /usr/libexec/gnome-settings-daemon ] ; then
    pgrep gnome-settings || /usr/libexec/gnome-settings-daemon &!
else
    whence -p gnome-settings-daemon &&
    pgrep gnome-settings || gnome-settings-daemon &!
fi




if [ -x  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings ||  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &!
elif [ -x /usr/libexec/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings || /usr/libexec/polkit-gnome-authentication-agent-1 &!
else
    whence -p polkit-gnome-authentication-agent-1 &&
    pgrep polkit-gnome || polkit-gnome-authentication-agent-1 &!
fi


pgrep gnome-keyring-d || gnome-keyring-daemon --start &!

DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/lib/gnome-online-accounts/goa-daemon &!
pgrep nm-applet || nm-applet --sm-disable &!


# pgrep empathy ||
# DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION empathy &!

if whence -p syndaemon ; then
    syndaemon -i 1 -d &!
    whence -p synclient && synclient TouchpadOff=1 &!
fi


foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    # gnome-keyring-daemon
    gnome-power-manager
    mail-notification
    blueman-adapters
    blueman-applet
    bluetoothd
    pidgin
    synergys
    ) {
        echo starting $prog >&2
        if whence -p $prog ; then
            pgrep $prog[0,15] || $prog &!
        fi

        echo B DBUS >&2
        pgrep -l dbus-daemon >&2

    }


# ~/bin/syncimap -r               # enable, done in rsetup/x/run
echo stumpwmrc end here >&2
