# Automatically generated by eev-rctoll
# in Wed Apr 19 19:37:29 IST 2017
echo '  Install: /home/s/hell/.emacs  <-  /home/s/hell/.eev/backup/.emacs.new'
cp /home/s/hell/.eev/backup/.emacs.new /home/s/hell/.emacs
echo '  Install: /home/s/hell/.bashrc  <-  /home/s/hell/.eev/backup/.bashrc.new'
cp /home/s/hell/.eev/backup/.bashrc.new /home/s/hell/.bashrc
echo '  Install: /home/s/hell/.zshrc  <-  /home/s/hell/.eev/backup/.zshrc.new'
cp /home/s/hell/.eev/backup/.zshrc.new /home/s/hell/.zshrc
echo '  Install: /home/s/hell/.gdbinit  <-  /home/s/hell/.eev/backup/.gdbinit.new'
cp /home/s/hell/.eev/backup/.gdbinit.new /home/s/hell/.gdbinit
echo '  Install: /home/s/hell/.tclshrc  <-  /home/s/hell/.eev/backup/.tclshrc.new'
cp /home/s/hell/.eev/backup/.tclshrc.new /home/s/hell/.tclshrc
