# Automatically generated by eev-rctoll
# in Wed Apr 19 19:37:29 IST 2017
echo '  Remove:  /home/s/hell/.emacs'
rm               /home/s/hell/.emacs
echo '  Restore: /home/s/hell/.bashrc  <-  /home/s/hell/.eev/backup/.bashrc.backup'
cp -p /home/s/hell/.eev/backup/.bashrc.backup /home/s/hell/.bashrc
echo '  Restore: /home/s/hell/.zshrc  <-  /home/s/hell/.eev/backup/.zshrc.backup'
cp -p /home/s/hell/.eev/backup/.zshrc.backup /home/s/hell/.zshrc
echo '  Restore: /home/s/hell/.gdbinit  <-  /home/s/hell/.eev/backup/.gdbinit.backup'
cp -p /home/s/hell/.eev/backup/.gdbinit.backup /home/s/hell/.gdbinit
echo '  Remove:  /home/s/hell/.tclshrc'
rm               /home/s/hell/.tclshrc
