#!/bin/zsh

if [ "x${HOST}" != "x" ] ; then
    __comp=sh

    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        mkdir -p ~/.setup/osetup/setup/rsetup.d/sh.d/run.d
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi





if [ -L ~/tmp -a ! -d ~/tmp ]
then
    mkdir -p $(readlink -m ~/tmp)
fi

if [ -L ~/.tmppublic -a ! -d ~/.tmppublic ]
then
    mkdir -p $(readlink -m ~/.tmppublic)
fi

if [ -d ~/.tmppublic ]
then
    mkdir -p ~/.tmppublic/Publish/html
    if [ ! -f ~/.tmppublic/Publish/html/.htaccess ]
    then
        echo "Options +Indexes" > ~/.tmppublic/Publish/html/.htaccess
    fi
fi

if [ -d ~/tmp -a ! -L ~/tmp/public ]
then
    ln -sf ~/.tmppublic ~/tmp/public
fi
