#!/bin/zsh

if [ "x${HOST}" != "x" ] ; then
    __comp=sh

    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        mkdir -p ~/.setup/osetup/setup/rsetup.d/sh.d/run.d
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi





if [ ! -d ~/tmp ]
then
    mkdir -p $(readlink -m ~/tmp)
fi
