#!/bin/zsh

# emacsclient -n -f ~/.emacs.d/server/general "$@"





if which emacs && which emacsclient ; then
    emacsclient -f ~/.emacs.d/server/general "$@"
elif which sensible-editor ; then
    sensible-editor "$@"
else
    vim "$@"
fi




