#!/bin/zsh -v

# emacsclient -n -f ~/.emacs.d/server/general "$@"

local prog=$(basename $0)
local alternative_editor
alternate_editors=( em zile mg jove sensible-editor vim joe )

local server_file="/home/s/hell/.emacs.d/server/general"

local rhost=s@ubuntu-sharad
local rproto=scpc
local rserver_file="/home/s/hell/.emacs.d/server/general"
local lhost=$(hostname -s)

debug=1

typeset -A args

if (( ${+rhost})) ; then
    args[-f]=${rserver_file}
else
    args[-f]=${server_file}
fi

# if [[ $prog =~ .*n$ ]]  ; then
#     args[-n]=""
# fi

if [ $prog = "xedn" -o $prog = "edn"  ]  ; then
    args[-n]=""
fi


if [ $# -eq 0 ] ; then
    args[-c]=""
fi

    foreach editor ( $alternate_editors )
    do
    if which $editor >& /dev/null ; then
        alted=$editor
        break
    fi
    done


case "$prog" in
    (general-editor*|editor*|ed*)
        args[-t]="";;
    (general-xeditor*|xeditor*|xed*)
        # args[-d]="$DISPLAY";;
        : ;;
    (*)  ;;
esac


foreach f ("$@" ) {
    [ -f $f ] && filegiven=
}

if which emacs >& /dev/null && which emacsclient >& /dev/null ; then
    if (( ${+rhost})) ; then
        # (( ${+debug} )) && echo eval ssh ${rhost} emacsclient ${(kv)args} ${filegiven--c} ${alted:+ -a $alted} /${rproto}:${lhost}:$(readlink -m "$@")
        # eval ssh ${rhost} emacsclient ${(kv)args} ${filegiven--c} ${alted:+ -a $alted} /${rproto}:${lhost}:$(readlink -m "$@")
        (( ${+debug} )) && echo eval ssh ${rhost} ${prog} /${rproto}:${lhost}:$(readlink -m "$@")
        eval ssh ${rhost} ${prog} /${rproto}:${lhost}:$(readlink -m "$@")
    else
        (( ${+debug} )) && echo eval emacsclient ${(kv)args} ${filegiven--c} ${alted:+ -a $alted} "$@"
        eval emacsclient ${(kv)args} ${filegiven--c} ${alted:+ -a $alted} "$@"
    fi
else

    $alted "$@"
fi
