#!/bin/zsh

# emacsclient -n -f ~/.emacs.d/server/general "$@"

prog=$(basename $0)


debug=0

typeset -A args


if which zile >& /dev/null ; then
    alted=zile
elif which mg >& /dev/null ; then
    alted=mg
elif which jove >& /dev/null ; then
    alted=jove
elif which sensible-editor >& /dev/null ; then
    alted=sensible-editor
else
    alted=vim
fi



args[-f]="~/.emacs.d/server/general"

if [[ $prog =~ .*n$ ]]  ; then
    args[-n]=""
fi


if [ $# -eq 0 ] ; then
    args[-c]=""
fi

case "$prog" in
    (general-editor*|editor*|ed*)
        args[-t]="";;
    (general-xeditor*|xeditor*|xed*)
        # args[-d]="$DISPLAY";;
        : ;;
    (*)  ;;
esac


foreach f ("$@" ) {
    [ -f $f ] && filegiven=
}

if which emacs >& /dev/null && which emacsclient >& /dev/null ; then
    (( ${+debug} )) && echo eval emacsclient ${(kv)args} ${filegiven--c} -a $alted "$@"
    eval emacsclient ${(kv)args} ${filegiven--c} -a $alted "$@"
elif which zile >& /dev/null ; then
    zile "$@"
elif which mg >& /dev/null ; then
    mg "$@"
elif which jove >& /dev/null ; then
    jove "$@"
elif which sensible-editor >& /dev/null ; then
    sensible-editor "$@"
else
    vim "$@"
fi
