#!/usr/bin/env zsh

# emacsclient -n -f ~/.emacs.d/server/general "$@"

prog=$(basename $0)

typeset -A args

args[-f]="~/.emacs.d/server/general"
args[-c]=""

case "$1" in
    (^*n$)
        args[ -n ]="$DISPLAY";;
    (^general-editor|editor|ed$)
        args[ -t ]="";;
    (^general-xeditor|xeditor|xed$)
        args[ -d ]="$DISPLAY";;
    (*)  ;;
esac

if which emacs && which emacsclient ; then
    echo emacsclient ${(kv)args} "$@"
elif which sensible-editor ; then
    sensible-editor "$@"
else
    vim "$@"
fi
