#!/bin/zsh

__comp=pmhibernateoff

if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
    cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}/
fi

[ -r ~/.rsetup/${__comp}/run.d/${HOST} ] && ~/.rsetup/${__comp}/run.d/${HOST}

unset __comp


if which $HOME/bin/ecryptfs-mount-private 2>&1 > /dev/null ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout -k 10 7 $HOME/bin/ecryptfs-mount-private
    fi
fi

sleep 10s

timeout -k 320 200 gksudo -gS ifup eth0
ifconfig eth0
print eth0 is up

mradio -c 6


whence -p xmodmap &&
xmodmap ~/.Xmodmaps/xmodmaprc-swap-alt-ctrl-caps=alt


# [ -r ~/.rsetup/ifup/run ] &&
# ~/.rsetup/ifup/run
