#!/usr/bin/env zsh

[ -r ~/.rsetup/pmhibernateoff/run.d/${HOST//.*} ] &&
~/.rsetup/pmhibernateoff/run.d/${HOST//.*}


if which $HOME/bin/ecryptfs-mount-private 2>&1 ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout 7 -k 10 $HOME/bin/ecryptfs-mount-private
    fi
fi



[ -r ~/.rsetup/ifup/run ] &&
~/.rsetup/ifup/run


