#!/usr/bin/env zsh

[ -r ~/.rsetup/pmhibernateoff/run.d/${HOST//.*} ] &&
~/.rsetup/pmhibernateoff/run.d/${HOST//.*}


if which $HOME/bin/ecryptfs-mount-private 2>&1 > /dev/null ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout -k 10 7 $HOME/bin/ecryptfs-mount-private
    fi
fi

sleep 10s

timeout -k 320 200 gksudo -gS ifup eth0
ifconfig eth0
print eth0 is up
# [ -r ~/.rsetup/ifup/run ] &&
# ~/.rsetup/ifup/run


