#!/bin/zsh

__comp=pmhibernateon

if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
    cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}/
fi

[ -r ~/.rsetup/${__comp}/run.d/${HOST} ] && ~/.rsetup/${__comp}/run.d/${HOST}

unset __comp

if which $HOME/bin/ecryptfs-mount-private 2>&1 > /dev/null ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout -k 10 7 ecryptfs-umount-private
    fi
fi

timeout -k 32 20 gksudo -gS ifdown eth0
ifconfig eth0
sleep 2s
print eth0 is down

ssh-add -D

pgrep mplayer && timeout  -k 4 2 echo "quit 0"  > /tmp/mplayer.fifo; # stop radio


# [ -r ~/.rsetup/ifdown/run ] &&
# ~/.rsetup/ifdown/run
