#!/usr/bin/env zsh

[ -r ~/.rsetup/pmhibernateon/run.d/${HOST//.*} ] &&
~/.rsetup/pmhibernateon/run.d/${HOST//.*}

if which $HOME/bin/ecryptfs-mount-private 2>&1 ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout 7 -k 10 $HOME/bin/ecryptfs-umount-private
    fi
fi


[ -r ~/.rsetup/ifdown/run ] &&
~/.rsetup/ifdown/run



