#!/bin/zsh

if which $HOME/bin/ecryptfs-mount-private 2>&1 > /dev/null ; then

    if [  -e $PRIVATE_DIR ] && [ "x" != "x$DISPLAY" ] ; then
        timeout -k 10 7 ecryptfs-umount-private
    fi
fi

# stop eth0 interface
timeout -k 32 20 gksudo -gS ifdown eth0
sleep 2s
print eth0 is down

# clear ssh keys
ssh-add -D

pgrep mplayer && timeout  -k 4 2 echo "quit 0"  > /tmp/mplayer.fifo; # stop radio



if [ "x${HOST}" = "x" ]
then
    HOST=$HOSTNAME
fi
if [ "x${HOST}" != "x" ]
then
    __comp=pmhibernateon

    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        mkdir ~/.rsetup/${__comp}/run.d/
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi
