#!/bin/zsh







pkill gnome-keyring

# pkill dbus-daemon

pkill ssh-agent

~/bin/syncimap -d               # it only get secinfo from x keyring; disable

foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    # gnome-keyring-daemon
    xautolock
    ) {
        echo A DBUS >&2
        pgrep -l dbus-daemon >&2

        echo $prog
        whence -p $prog &&
        pgrep $prog[0,15] && pkill $prog[0,15]

        echo B DBUS >&2
        pgrep -l dbus-daemon >&2

    }



__comp=xlogout

if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
    cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
fi

[ -r ~/.rsetup/${__comp}/run.d/${HOST} ] && ~/.rsetup/${__comp}/run.d/${HOST}

unset __comp
