#!/usr/bin/env zsh







pkill -u "$(id -u)" gnome-keyring

# pkill -u "$(id -u)" dbus-daemon

nlogin=$(w -h $LOGNAME | grep -cv pts)
if [ ${SSH_AGENT_PID+1} == 1 ]; then
    ssh-add -D
    if (( $nlogin == 1 )) ; then

        notify "killing ssh-agent"

        # ssh-agent -k > /dev/null 2>&1
        # # it kill all other login's ssh-agent
        # kill $SSH_AGENT_PID
        # pkill -u "$(id -u)" ssh-agent
        # unset SSH_AGENT_PID
        # unset SSH_AUTH_SOCK
    fi
elif (( $nlogin == 1 )) ; then
    # it kill all other login's ssh-agent
    #pkill -u "$(id -u)" ssh-agent
fi


~/bin/syncimap -d               # it only get secinfo from x keyring; disable


if whence -p compton >& /dev/null
then
    if pgrep -u "$(id -u)" compton >& /dev/null
    then
        pkill -u "$(id -u)" compton
    fi
fi

if whence -p xcompmgr >& /dev/null
then
    if pgrep -u "$(id -u)" xcompmgr >& /dev/null
    then
        pkill -u "$(id -u)" xcompmgr
    fi
fi


foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    # gnome-keyring-daemon
    xautolock
    ) {
        echo A DBUS >&2
        pgrep -u "$(id -u)" -l dbus-daemon >&2

        echo $prog
        whence -p $prog &&
        pgrep -u "$(id -u)" $prog[0,15] && pkill -u "$(id -u)" $prog[0,15]

        echo B DBUS >&2
        pgrep -u "$(id -u)" -l dbus-daemon >&2

    }

if [ "x${HOST}" = "x" ]
then
    HOST=$HOSTNAME
fi
if [ "x${HOST}" != "x" ]
then
    __comp=xlogout


    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        mkdir -p ~/.rsetup/${__comp}/run.d/
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi
