
* Setup user TODOs
** Utilities
*** Add proper support for gitwatch auto-checkin and updates
*** Add support to not lock screen if video is playing.
** Terminal
*** URXVT add support for checking inactivity activity, activity followed by inactivity, inactivity followed by activity.
**** We need to implement support for dialog box to receive character strings.
** Internet
*** Browser
**** Add support for auto bookmark based on based on activity time on site

**** Add support for adding session bookmarks
**** Add support to detect of focused buffer running video or Youtube than not lock screen
** Security
*** Keymanager gpg-agent ssh-agent and gnome-keyring etc need to be locked or identities need to be flushed on inactivity or locking.
    again need to be asked when logging-in back.
** Automation
*** Script to run heavy tasks on detecting inactivity and low system usages.
    In line of cron, anacron, it will be inactivity-cron
** UI => GUI
*** WM
**** stumpwm
***** Add support for sending SIG especially SIGSTOP and SIGCONT to window
***** move-focus [left|right|down|up] same way move-focus-to-window-maybe [left|right|down|up]
To directly go to window with frame
Here I also got analogical method which is followed by many like swiftkey
which guess some word if user delete back than revert back to original typed.

some kind of similar thing we could put here move-focus DIR jump to WIN in DIR but if user do following reverse operation
than come back to old behaviour.

*** On Screen Display or conky or OSD kind of information rendering system for wide information
    with capability for interactivity.

** Emacs

*** Automate Recurring
**** DONE forgive/them should be automated
     CLOSED: [2018-06-15 Fri 12:33]
     :LOGBOOK:
     - State "DONE"       from              [2018-06-15 Fri 12:33]
     :END:
** Explore rofi and dmenu
* Setup machine
** Some outgoing relay smtp server allow from a specific Network
for this configure postfix to bind using wlan0 ip
** Setup dovecote to store mail attachment separately
follow https://www.dovecot.org/list/dovecot/2016-February/103077.html
* Setup Emacs
** Helm shortcut for long paths and many things
 #+BEGIN_SRC elisp
 ;; https://stackoverflow.com/questions/19283368/how-can-i-open-quickly-a-file-in-emacs
 (defun my-helm-omni (&rest arg)
   ;; just in case someone decides to pass an argument, helm-omni won't fail.
   (interactive)
   (helm-other-buffer
    (append '(helm-c-source-buffers-list ;; list of all open buffers
              helm-c-source-recentf)    ;; all recent files

            ;; projectile errors out if you're not in a project
            (if (projectile-project-p) ;; so look before you leap
                '(helm-source-projectile-files-list
                  helm-source-projectile-recentf-list
                  helm-source-projectile-buffers-list)
                '())

            '(
              helm-c-source-files-in-current-dir ;; files in current directory
              helm-c-source-locate               ;; file anywhere
              helm-c-source-bookmarks            ;; bookmarks too
              helm-c-source-buffer-not-found))     ;; ask to create a buffer otherwise

    "*helm-omni*"))
 #+END_SRC
*** Emacs ideas (long term)
** Emacs create a package aka plugin to directly contribute to GitHub project of any el file
Here can be public rating to manage patch
A abstract system which follow project guidelines for patch submission directly to project.
It will be really interesting.

It can also server as a Great POC how to expand participation from big number of peoples.

When this is completed we will mindshare contribution manager
Will be responsible to find related project' repository and guidelines for code be worked.
** mindshare contribution manager
** Support for adding D-O-N-E task
** Support for task to have information about who requested, when request, where requested


* Occasionally remind

** When not able to start or concentrate on work start doing regular work
e.g. migrating old Emacs configuration to new Spacemacs.

** Post shall script to notify long running command especially when terminal window do not have focus and visibility should notify
command exit status.

** Create framework to run necessary whole build a when system is idle or build dir is not actively getting used
(could be known using fuser or lsfs commands.)

** Make optimized script in place of git apply patch which takes lots of time.
** Specialized less or more program in line of silversearcher ag for grep, to view bigger log files
1. support for timestamp
2. support for multiple log files with timestamps.



* Misc
** stumpwm Change per group current directory in stumpwm
** stumpwm or anywm

In case of wm hanging
Arrange a handy terminal or console where we can atleast kill wm.
** stumpwm music per window
** Musical (instrumental) desktop
Whenever a window is selected music associated with that window
starts playing.

use xprop
** stumpwm command mode improvement
with C-baqckquote go into command till enter pressed.
