(source gnu)
(source melpa)

(package "rs-gnus-exts" "0.2.1" "rs-gnus-exts")

(development
 (depends-on "stripe-buffer")
 (depends-on "f")
 (depends-on "ecukes")
 (depends-on "ert-runner")
 (depends-on "el-mock"))
