
;; custom.el


;;{{{ custom-set-variables
(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(auto-compression-mode t nil (jka-compr))
 '(bbdb-check-zip-codes-p nil)
 '(bbdb-default-country "INDIA")
 '(bbdb-north-american-phone-numbers-p nil)
 '(blink-cursor-mode t)
 '(bmkp-last-as-first-bookmark-file "~/.emacs.bmk")
 '(calendar-mark-diary-entries-flag t)
 '(calendar-view-diary-initially-flag t)
 '(canlock-password "93d68f0366b0f7bb850c020c9b41a029023b0526")
 '(case-fold-search t)
 '(color-theme-selection "Arjen" nil (color-theme))
 '(column-number-mode t)
 '(current-language-environment "ASCII")
 '(default-input-method "english-dvorak")
 '(diary-entry-marker "+")
 '(diary-file "~/.Organize/emacs/diary/diary")
 '(diary-mail-addr "sh4r4d@gmail.com")
 '(display-time-24hr-format nil)
 '(display-time-day-and-date t)
 '(display-time-mail-face (quote default))
 '(display-time-mail-file nil)
 '(display-time-mode t)
 '(ecb-auto-activate nil)
 '(ecb-layout-window-sizes (quote (("sharad-leftright-analyse-etc-reverse" (ecb-directories-buffer-name 0.1179245283018868 . 0.4909090909090909) (ecb-analyse-buffer-name 0.1179245283018868 . 0.4909090909090909) (ecb-methods-buffer-name 0.17452830188679244 . 0.38181818181818183) (ecb-sources-buffer-name 0.17452830188679244 . 0.2909090909090909) (ecb-history-buffer-name 0.17452830188679244 . 0.3090909090909091)))))
 '(ecb-major-modes-show-or-hide (quote ((js-mode cperl-mode perl-mode emacs-lisp-mode lisp-mode c-mode shell-script-mode) mail-mode fundamental-mode planner-mode)))
 '(ecb-options-version "2.40")
 '(ecb-other-window-behavior (quote edit-and-compile))
 '(ecb-toggle-layout-sequence (quote ("sharad-leftright-analyse" "left9" "left14")))
 '(erc-modules (quote (autoaway autojoin button capab-identify completion hecomplete dcc fill identd irccontrols keep-place list log match menu move-to-prompt netsplit networks noncommands notify page readonly replace ring scrolltobottom services smiley sound stamp spelling track truncate unmorse xdcc)))
 '(global-font-lock-mode t nil (font-lock))
 '(gnus-registry-install t)
 '(gnus-treat-from-picon (quote head))
 '(gnus-treat-mail-picon (quote head))
 '(gnus-treat-newsgroups-picon (quote head))
 '(ido-enable-tramp-completion nil)
 '(ido-use-filename-at-point (quote guess))
 '(load-home-init-file t t)
 '(menu-bar-mode nil)
 '(mm-inline-text-html-with-images t)
 '(newsticker-url-list (quote (("OSNews" "http://www.osnews.com/feeds" nil nil nil))))
 '(org-agenda-files (file-expand-wildcards "~/.Organize/emacs/org/*/*.org"))
 '(org-agenda-include-diary t)
 '(planner-annotation-strip-directory t)
 '(planner-annotation-use-relative-file t)
 '(planner-appt-forthcoming-look-at-cyclic-flag t)
 '(planner-appt-schedule-cyclic-behaviour (quote future))
 '(planner-appt-update-appts-on-save-flag t)
 '(planner-create-section-function (quote planner-create-at-bottom))
 '(planner-cyclic-diary-nag t)
 '(planner-diary-appts-file "~/.Organize/emacs/diary/diary")
 '(planner-diary-cal-desk-file "~/.Organize/emacs/diary/diary")
 '(planner-diary-exclude-appts-from-diary nil)
 '(planner-diary-file "~/.Organize/emacs/diary/diary")
 '(planner-diary-number-of-days 5)
 '(planner-diary-private-file "~/.Organize/emacs/diary/private")
 '(planner-diary-private-number-of-days 1)
 '(planner-diary-public-file "~/.Organize/emacs/diary/public")
 '(planner-diary-public-number-of-days 1)
 '(planner-diary-use-appts t)
 '(planner-diary-use-cal-desk t)
 '(planner-diary-use-diary t)
 '(planner-diary-use-private-diary t)
 '(planner-diary-use-public-diary t)
 '(planner-expand-name-favor-future-p t)
 '(planner-renumber-notes-automatically t)
 '(planner-renumber-tasks-automatically t)
 '(planner-sections (quote ((tasks . "Tasks") (notes . "Notes") (diary . "Diary") (env . "Environment"))))
 '(planner-tasks-file-behavior (quote close))
 '(safe-local-variable-values (quote ((folded-file . t) (auto-fill-mode))))
 '(save-abbrevs t)
 '(save-place t nil (saveplace))
 '(scroll-conservatively 4)
 '(session-set-file-name-exclude-regexp "/\\.overview\\|.session\\|News/\\|\\.Organize/")
 '(session-use-package t nil (session))
 '(show-paren-mode t nil (paren))
 '(speedbar-directory-unshown-regexp "^\\(CVS\\|RCS\\|SCCS\\|.deps\\)\\'")
 '(speedbar-frame-parameters (quote ((minibuffer) (width . 20) (border-width . 0) (menu-bar-lines . 0) (tool-bar-lines . 0) (unsplittable . t) (set-background-color "black"))))
 '(speedbar-supported-extension-expressions (quote (".[ch]\\(\\+\\+\\|pp\\|c\\|h\\|xx\\)?" ".tex\\(i\\(nfo\\)?\\)?" ".el" ".emacs" ".l" ".lsp" ".p" ".java" ".f\\(90\\|77\\|or\\)?" ".ad*" ".p[lm]" ".tcl" ".m" ".scm" ".pm" ".py" ".g" ".s?html" "[Mm]akefile\\(\\.in\\|am\\)?" "configure.ac" ".ml*" ".tig" ".\\(ll\\|yy\\)")))
 '(text-mode-hook (quote (turn-on-auto-fill text-mode-hook-identify)))
 '(tramp-fish-method "fish")
 '(tramp-verbose 10)
 '(uniquify-buffer-name-style (quote forward) nil (uniquify))
 '(vc-follow-symlinks nil)
 '(view-read-only t)
 '(w3m-default-display-inline-images t)
 '(weblogger-config-alist (quote (("default" "http://www.livejournal.com/interface/blogger/" "sh4r4d" "" "sh4r4d"))))
 '(yas/trigger-key "C->"))
;;}}}


;;{{{ custom-set-faces
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(background "blue")
 '(etask-face-day-marker ((((class color)) (:foreground "white"))))
 '(etask-face-normaltask ((((class color)) (:foreground "white"))))
 '(etask-face-normaltaskname-behind-schedule ((((class color)) (:foreground "white" :weight bold))))
 '(etask-face-normaltaskname-completed ((((class color)) (:foreground "white" :strike-through t))))
 '(etask-face-status-ok ((((class color)) (:foreground "white" :weight bold))))
 '(font-lock-builtin-face ((((class color) (background dark)) (:foreground "Turquoise"))))
 '(font-lock-comment-face ((t (:foreground "MediumAquamarine"))))
 '(font-lock-constant-face ((((class color) (background dark)) (:bold t :foreground "DarkOrchid"))))
 '(font-lock-doc-string-face ((t (:foreground "green2"))))
 '(font-lock-function-name-face ((t (:foreground "SkyBlue"))))
 '(font-lock-keyword-face ((t (:bold t :foreground "CornflowerBlue"))))
 '(font-lock-preprocessor-face ((t (:italic nil :foreground "CornFlowerBlue"))))
 '(font-lock-reference-face ((t (:foreground "DodgerBlue"))))
 '(font-lock-string-face ((t (:foreground "LimeGreen"))))
 '(font-lock-type-face ((t (:foreground "#9290ff"))))
 '(font-lock-variable-name-face ((t (:foreground "PaleGreen"))))
 '(font-lock-warning-face ((((class color) (background dark)) (:foreground "yellow" :background "red"))))
 '(gnus-summary-normal-unread ((t (:foreground "light salmon" :inverse-video nil :slant italic :weight bold))))
 '(highlight ((t (:background "CornflowerBlue"))))
 '(list-mode-item-selected ((t (:background "gold"))))
 '(makefile-space ((t (:background "wheat"))))
 '(makefile-space-face ((t (:background "wheat"))) t)
 '(mode-line ((t (:background "Navy"))))
 '(paren-match ((t (:background "darkseagreen4"))) t)
 '(region ((t (:background "DarkSlateBlue"))))
 '(show-paren-match ((t (:foreground "black" :background "wheat"))))
 '(show-paren-mismatch ((((class color)) (:foreground "white" :background "red"))))
 '(speedbar-button-face ((((class color) (background dark)) (:foreground "green4"))))
 '(speedbar-directory-face ((((class color) (background dark)) (:foreground "khaki"))))
 '(speedbar-file-face ((((class color) (background dark)) (:foreground "cyan"))))
 '(speedbar-tag-face ((((class color) (background dark)) (:foreground "Springgreen"))))
 '(trailing-whitespace ((((class color) (background light)) (:foreground unspecified :strike-through "chartreuse2"))))
 '(vhdl-speedbar-architecture-selected-face ((((class color) (background dark)) (:underline t :foreground "Blue"))))
 '(vhdl-speedbar-entity-face ((((class color) (background dark)) (:foreground "darkGreen"))))
 '(vhdl-speedbar-entity-selected-face ((((class color) (background dark)) (:underline t :foreground "darkGreen"))))
 '(vhdl-speedbar-package-face ((((class color) (background dark)) (:foreground "black"))))
 '(vhdl-speedbar-package-selected-face ((((class color) (background dark)) (:underline t :foreground "black"))))
 '(widget-field ((((class grayscale color) (background light)) (:background "DarkBlue")))))
;;}}}


