#!/usr/bin/env zsh

if [ "x${HOST}" = "x" ]
then
    HOST=$HOSTNAME
fi
if [ "x${HOST}" != "x" ]
then
    __comp=logout


    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        mkdir -p ~/.rsetup/${__comp}/run.d/
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi



# for startup in logout ; do
#    [ -r ~/.rsetup/$startup/env ] && . ~/.rsetup/$startup/env
# done
# for startup in logout ; do
#    [ -r ~/.rsetup/$startup/run ] && ~/.rsetup/$startup/run
# done

# cleaup home dir [only]
~/bin/tidydir ~

if [ ${SSH_AGENT_PID+1} == 1 ]; then
    ssh-add -D
    # no killing
    # ssh-agent -k > /dev/null 2>&1
    # ssh-agent -k
    # # it kill all other login's ssh-agent
    # pkill ssh-agent
    # ssh-agent -k
    # kill $SSH_AGENT_PID
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
fi

if pgrep leave >& /dev/null ; then
    pkill leave >& /dev/null
    pkill -9 leave >& /dev/null
fi

## updae git if no current change present.
if ! command ps f -u $USER | grep -v grep | grep gitwatch
then
    GITWATCHPID=$(command ps f -u $USER | grep -v grep | grep gitwatch | cut -d' ' -f1)
    if [ -n "$GITWATCHPID" ]
    then
        kill $GITWATCHPID
    fi
fi
