#!/bin/zsh

if [ "x${HOST}" != "x" ] ; then
    __comp=logout


    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        mkdir ~/.rsetup/${__comp}/run.d/
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi



# for startup in logout ; do
#    [ -r ~/.rsetup/$startup/env ] && . ~/.rsetup/$startup/env
# done
# for startup in logout ; do
#    [ -r ~/.rsetup/$startup/run ] && ~/.rsetup/$startup/run
# done


if [ ${SSH_AGENT_PID+1} == 1 ]; then
    ssh-add -D
    ssh-agent -k > /dev/null 2>&1
    kill $SSH_AGENT_PID
    unset SSH_AGENT_PID
    unset SSH_AUTH_SOCK
    # it kill all other login's ssh-agent
    # pkill ssh-agent
fi

if pgrep leave >& /dev/null ; then
    pkill leave >& /dev/null
    pkill -9 leave >& /dev/null
fi
