#!/usr/bin/env zsh

__comp=eev
__subcomp=run

if [ "x${HOST}" = "x" ]
then
    HOST=$HOSTNAME
fi

if [ ! -d "/tmp/user/$(id -u)" ]
then
    mkdir -p "/tmp/user/$(id -u)"
fi

if [ "x${HOST}" != "x" ]
then
    __comp=eev

    if [ -d ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        rm -rf ~/.rsetup/${__comp}/run.d/${HOST}
    fi
    if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        mkdir -p ~/.setup/osetup/setup/rsetup.d/${__comp}.d/run.d
        cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    if [ -r ~/.rsetup/${__comp}/run.d/${HOST} ]
    then
        ~/.rsetup/${__comp}/run.d/${HOST}
    fi

    unset __comp
else
    print env var HOST is not set $HOST
fi


