#!/usr/bin/env zsh
# give access to mpd

if whence xte ; then
    xte <<EOF
mousemove 42 42
EOF
fi

[ -x /usr/libexec/at-spi-registryd ] && DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/libexec/at-spi-registryd &!

# whence -p gnome-screensaver &&
# pgrep gnome-screensaver ||
# gnome-screensaver &!

if [ -x /usr/lib/gnome-settings-daemon/gnome-settings-daemon ] ; then
    pgrep gnome-settings || /usr/lib/gnome-settings-daemon/gnome-settings-daemon &!
elif [ -x /usr/libexec/gnome-settings-daemon ] ; then
    pgrep gnome-settings || /usr/libexec/gnome-settings-daemon &!
else
    whence -p gnome-settings-daemon &&
    pgrep gnome-settings || gnome-settings-daemon &!
    sleep 1s;
fi




if [ -x  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings ||  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &!
    sleep 1s;
elif [ -x /usr/libexec/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings || /usr/libexec/polkit-gnome-authentication-agent-1 &!
    sleep 1s;
else
    whence -p polkit-gnome-authentication-agent-1 &&
    pgrep polkit-gnome || polkit-gnome-authentication-agent-1 &!
    sleep 1s;
fi


pgrep gnome-keyring-d || gnome-keyring-daemon --start &!
sleep 1s;

DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/lib/gnome-online-accounts/goa-daemon &!
sleep 1s;
pgrep nm-applet || nm-applet --sm-disable &!
sleep 1s;


# pgrep empathy ||
# DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION empathy &!

if whence -p syndaemon ; then
    syndaemon -i 1 -d &!
    sleep 1s;
    whence -p synclient && synclient TouchpadOff=1 &!
    sleep 1s;
fi

if [ -x /usr/lib/gvfs/gvfsd ] ; then
    ! pgrep gvfsd || /usr/lib/gvfs/gvfsd -r ~/.gvfs &!
fi

foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    # gnome-keyring-daemon
    gnome-power-manager
    mail-notification
    blueman-adapters
    blueman-applet
    bluetoothd
    pidgin
    synergys
    ) {
        if whence -p $prog && ! pgrep $prog[0,15] ; then
            $prog &!
            echo started $prog >&2
	    pgrep $prog[0,15]
            sleep 1s;
        else
            echo Not starting $prog >&2
        fi
    }


if whence xte ; then
    xte <<EOF
mousemove 42 42
EOF
fi

xautolock -locknow &!

# ~/bin/syncimap -r               # enable, done in rsetup/x/run
echo stumpwmrc end here >&2

atq
if [ $(atq | cut -f1 | wc -l) -gt 0 ] ; then
    atrm  $(atq | cut -f1)
fi


# WM specific setup
~/bin/wallpaper-setup
~/bin/stumpwm-setup


[ -r ~/.rsetup/wmlogin/run.d/${HOST//.*} ] &&
~/.rsetup/wmlogin/run.d/${HOST//.*}




