#!/bin/zsh


#!/usr/bin/env zsh
# give access to mpd

if whence xte ; then
    xte <<EOF
mousemove 42 42
EOF
fi

if [ -x /usr/libexec/at-spi-registryd ] ; then
    DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/libexec/at-spi-registryd &!
 elif [  -x  /usr/lib/at-spi2-core/at-spi2-registryd ] ; then
    DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/lib/at-spi2-core/at-spi2-registryd &!
fi


# whence -p gnome-screensaver &&
# pgrep gnome-screensaver ||
# gnome-screensaver &!

if [ -x /usr/lib/gnome-settings-daemon/gnome-settings-daemon ] ; then
    pgrep gnome-settings >& /dev/null || /usr/lib/gnome-settings-daemon/gnome-settings-daemon &!
elif [ -x /usr/libexec/gnome-settings-daemon ] ; then
    pgrep gnome-settings >& /dev/null || /usr/libexec/gnome-settings-daemon &!
else
    whence -p gnome-settings-daemon &&
    pgrep gnome-settings >& /dev/null || gnome-settings-daemon &!
    sleep 1s;
fi




if [ -x  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings >& /dev/null ||  /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &!
    sleep 1s;
elif [ -x /usr/libexec/polkit-gnome-authentication-agent-1 ] ; then
    pgrep gnome-settings >& /dev/null || /usr/libexec/polkit-gnome-authentication-agent-1 &!
    sleep 1s;
else
    whence -p polkit-gnome-authentication-agent-1 >& /dev/null &&
    pgrep polkit-gnome >& /dev/null || polkit-gnome-authentication-agent-1 &!
    sleep 1s;
fi


pgrep gnome-keyring-d >& /dev/null || gnome-keyring-daemon --start &!
sleep 1s;

DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION /usr/lib/gnome-online-accounts/goa-daemon &!
sleep 1s;
pgrep nm-applet >& /dev/null || nm-applet --sm-disable &!
sleep 1s;


# pgrep empathy ||
# DISPLAY=:0.0 dbus-launch --autolaunch=$MY_DBUS_SESSION empathy &!

if whence -p syndaemon >& /dev/null ; then
    syndaemon -i 1 -d &!
    sleep 1s;
    whence -p synclient >& /dev/null &&
    pgrep synclient >& /dev/null ||
    synclient TouchpadOff=1 &!
    sleep 1s;
fi

if [ -x /usr/lib/gvfs/gvfsd ] ; then
    ! pgrep gvfsd || /usr/lib/gvfs/gvfsd -r ~/.gvfs &!
fi

foreach prog (
    ## it is automatically started by gdm, so no need to start it.
    # gnome-keyring-daemon
    gnome-power-manager
    mail-notification
    blueman-adapters
    blueman-applet
    bluetoothd
    pidgin
    empathy
    synergys
    ) {
        if whence -p $prog >& /dev/null && ! pgrep $prog[0,15] >& /dev/null ; then
            $prog &!
            echo started $prog >&2
	    pgrep $prog[0,15] >&2
            sleep 1s;
        else
            print Not starting $prog >&2
        fi
    }


if whence xte ; then
    xte <<EOF
mousemove 42 42
EOF
fi

pgrep xautolock >& /dev/null && xautolock -locknow &!

# ~/bin/syncimap -r               # enable, done in rsetup/x/run
echo stumpwmrc end here >&2

atq
if [ $(atq | cut -f1 | wc -l) -gt 0 ] ; then
    atrm  $(atq | cut -f1)
fi


# WM specific setup
~/bin/wallpaper-setup
~/bin/stumpwm-setup


[ -r ~/.rsetup/wmlogin/run.d/${HOST//.*} ] &&
~/.rsetup/wmlogin/run.d/${HOST//.*}
