#!/bin/zsh

__comp=wscreenlockoff

if [ ! -x ~/.rsetup/${__comp}/run.d/${HOST} ] ; then
    cp ~/.rsetup/${__comp}/run.tmpl ~/.rsetup/${__comp}/run.d/${HOST}
fi

[ -r ~/.rsetup/${__comp}/run.d/${HOST} ] && ~/.rsetup/${__comp}/run.d/${HOST}

unset __comp
