# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1272248887);
user_pref("app.update.lastUpdateTime.background-update-timer", 1272248886);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1272248886);
user_pref("extensions.enabledItems", "");
user_pref("extensions.lastAppVersion", "0.9.1 (Debian-0.9.1+git100220-1ubuntu3)");
user_pref("extensions.update.notifyUser", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("spellchecker.dictionary", "en-US");
// https://superuser.com/questions/697018/how-to-disable-popups-in-firefox-without-add-ons
user_pref("dom.disable_open_during_load", false);



// get color at http://www.webmonkey.com/2010/02/color_charts/
if (false) {
    user_pref("browser.display.use_system_colors", false);
    user_pref("browser.active_color", "#EE0000");
    user_pref("browser.anchor_color", "#0000EE");
    // // user_pref("browser.display.background_color", "#99CC99");
    // user_pref("browser.display.background_color", "#669933");
    // // user_pref("browser.display.foreground_color", "#000000");
    // user_pref("browser.display.foreground_color", "#003333");

    // user_pref("browser.visited_color", "#551A8B");
    user_pref("browser.visited_color", "#660033");


}
