# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1332358554);
user_pref("app.update.lastUpdateTime.background-update-timer", 1290846548);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1332358674);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1332358554);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1332358554);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.display.background_color", "#FFFFFF");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
user_pref("extensions.enabledItems", "{6f9d85e0-794d-11dd-ad8b-0800200c9a66}:0.4,mozrepl@hyperstruct.net:2009122217");
user_pref("extensions.installCache", "[]");
user_pref("extensions.lastAppVersion", "0.9.3 (Debian-0.9.3+git110307-2ubuntu1)");
user_pref("extensions.mozrepl.autoStart", true);
user_pref("extensions.newAddons", "{6f9d85e0-794d-11dd-ad8b-0800200c9a66},mozrepl@hyperstruct.net");
user_pref("extensions.update.notifyUser", false);
user_pref("idle.lastDailyNotification", 1289929857);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.external.mailto", true);
user_pref("places.history.expiration.transient_current_max_pages", 108599);
user_pref("spellchecker.dictionary", "en-US");
