# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

<<<<<<< HEAD
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1290846548);
user_pref("app.update.lastUpdateTime.background-update-timer", 1290846548);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1290846548);
user_pref("browser.display.background_color", "#669933");
user_pref("browser.display.foreground_color", "#003333");
user_pref("browser.visited_color", "#660033");
=======
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1320580501);
user_pref("app.update.lastUpdateTime.background-update-timer", 1290846548);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1320580621);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1320580501);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1320602101);
user_pref("browser.active_color", "#EE0000");
user_pref("browser.anchor_color", "#0000EE");
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size_cached_value", 640000);
user_pref("browser.display.background_color", "#FFFFFF");
user_pref("browser.display.foreground_color", "#000000");
user_pref("browser.display.use_system_colors", false);
user_pref("browser.visited_color", "#551A8B");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 3);
>>>>>>> 6c943ac23291de1c8e4be0bcf7b0d5cb78e24e7a
user_pref("extensions.enabledItems", "{6f9d85e0-794d-11dd-ad8b-0800200c9a66}:0.4,mozrepl@hyperstruct.net:2009122217");
user_pref("extensions.installCache", "[]");
user_pref("extensions.lastAppVersion", "0.9.3 (Debian-0.9.3+git110307-2ubuntu1)");
user_pref("extensions.mozrepl.autoStart", true);
user_pref("extensions.newAddons", "{6f9d85e0-794d-11dd-ad8b-0800200c9a66},mozrepl@hyperstruct.net");
user_pref("extensions.update.notifyUser", false);
<<<<<<< HEAD
user_pref("idle.lastDailyNotification", 1289929857);
=======
user_pref("idle.lastDailyNotification", 1320580738);
>>>>>>> 6c943ac23291de1c8e4be0bcf7b0d5cb78e24e7a
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.protocol-handler.external.mailto", true);
user_pref("places.database.lastMaintenance", 1320580738);
user_pref("places.history.expiration.transient_current_max_pages", 108600);
user_pref("spellchecker.dictionary", "en-US");
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1320580738);
