#!/usr/bin/env zsh

parttable=~/.backup/sda.gpt

mkdir -p $(dirname $parttable )
sudo sgdisk -b $parttable /dev/sda
mail $MAILTO -s '[auto] part table' <<EOF


~| uuencode $parttable filename.txt


EOF
