#!/bin/bash



function main() {
    interval=10m
    action=pm-hibernate
    process_arg $@

    if ! zenity --question --timeout=20 --text="Do you want system to $action after ${interval}?" ; then
        rm -f $enable_file;
        notify $pgm disabled;
        exit 0;
    else
        notify $pgm will $action after $interval;
    fi

    poweroffsys

}

function poweroffsys() {
    sleep $interval

    if [ -e $enable_file ] ; then
        if [ -z "$noaction" ] ; then
            sudo $action
        else
            notify sudo poweroff
        fi
    else
        notify not poweringoff system.
    fi
}

function process_arg() {

    enable_file=~/.var/comm/disable/$pgm
    set -- $(getopt -n $pgm -o hscivwent:a: -- $@)
    while [ $# -gt 0 ]
    do
        case $1 in
            (-t) eval interval=$2; shift;;
            (-a) eval action=$2; shift;;
            (-n) noaction=1;;
            (-i) interactive=1;;
            (-v) verbose=1;;
            (-c)
                 if mkdir -p $(dirname $enable_file); touch $enable_file ; then
                     notify "will poweroff to avoid poweroff run \n\t\t $pgm -s "
                 fi
                 exit;;
            (-s) rm -f $enable_file;
                 notify $pgm disabled;
                 exit;;
            (-w) warn=1;;
            (-e) error=1;;
            (-h) help;
                 exit;;
            (--) shift; break;;
            (-*) echo "$0: error - unrecognized option $1" 1>&2; help; exit 1;;
            (*)  break;;
        esac
        shift
    done
}

function help() {
    cat <<'EOF'
            -a: eval account=$2; shift;;
            -i: interactive=1;;
            -v: verbose=1;;
            -d: touch $enable_file;;
            -r: rm -f $enable_file;;
            -w: warn=1;;
            -e: error=1;;
            -h: help;;
EOF

}

function warn() {
    if [ $warn ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function verbose() {
    if [ $verbose ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function notify() {
    if [ -t 1 ] ; then
        echo -e "${pgm}" "$*"
    else
        notify-send "${pgm}" "$*"
    fi
    logmsg "$*"
}

function logmsg() {
    #creating prolem
    logger -i -p local1.notice -t ${pgm}  -- "$*"
}



pgm=$(basename $0)

main $@
