#!/bin/bash



function main() {



    process_arg $@

}

function poweroffsys() {
    if [ -e $enable_file ] ; then
        sudo poweroff
    else
        notify no poweringoff system.
    fi
}

function process_arg() {

    enable_file=~/.var/comm/disable/$pgm
    set -- $(getopt -n $pgm -o hscivweg -- $@)
    while [ $# -gt 0 ]
    do
        case $1 in
            (-a) eval account=$2; shift;;
            (-i) interactive=1;;
            (-v) verbose=1;;
            (-g) poweroffsys ;;
            (-c)
                 if mkdir -p $(dirname $enable_file); touch $enable_file ; then
                     notify "will poweroff to avoid poweroff run \n\t\t $pgm -s "
                 fi
                 exit;;
            (-s) rm -f $enable_file;
                 echo $pgm disabled;
                 exit;;
            (-w) warn=1;;
            (-e) error=1;;
            (-h) help;
                 exit;;
            (--) shift; break;;
            (-*) echo "$0: error - unrecognized option $1" 1>&2; help; exit 1;;
            (*)  break;;
        esac
        shift
    done
}

function help() {
    cat <<'EOF'
            -a: eval account=$2; shift;;
            -i: interactive=1;;
            -v: verbose=1;;
            -d: touch $enable_file;;
            -r: rm -f $enable_file;;
            -w: warn=1;;
            -e: error=1;;
            -h: help;;
EOF

}

function warn() {
    if [ $warn ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function verbose() {
    if [ $verbose ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function notify() {
    if [ -t 1 ] ; then
        echo -e "${pgm}" "$*"
    else
        notify-send "${pgm}" "$*"
    fi
    logmsg "$*"
}

function logmsg() {
    #creating prolem
    logger -i -p local1.notice -t ${pgm}  -- "$*"
}



pgm=$(basename $0)

main $@

