#!/bin/bash



function main() {

    process_arg $@

    # ask
    yad --image "dialog-question" --title "Alert"  --button=gtk-no:1 --button=gtk-yes:0  --timeout=$timeout --text="Do you want system to $action after ${interval}?" ;

    retval=$?

    case $retval in
        (0|70) notify $pgm will $action after $interval;;
        (*)
            rm -f $disable_file;
            notify $pgm disabled;
            exit 0;;
    esac

    poweroffsys

}

function poweroffsys() {
    sleep $interval

    if [ -e $disable_file ] ; then
        notify not poweringoff system.
    else
        if [ -z "$noaction" ] ; then
            [ -n "$debug" ] && notify sudo $action if noaction $noaction
            [ -n "$debug" ] || sudo $action
        else
            [ -n "$debug" ] && notify sudo $action else noaction $noaction
            [ -n "$debug" ] || notify sudo $action
        fi
    fi
}

function process_arg() {

    disable_file=~/.var/comm/disable/$pgm
    interval=10m
    timeout=20
    action=pm-hibernate
    unset debug
    unset noaction

    set -- $(getopt -n $pgm -o dhscivwent:a:o: -- $@)
    while [ $# -gt 0 ]
    do
        case $1 in
            (-o) eval timeout=$2; shift;;
            (-t) eval interval=$2; shift;;
            (-a) eval action=$2; shift;;
            (-d) debug=1;;
            (-n) noaction=1;;
            (-i) interactive=1;;
            (-v) verbose=1;;
            (-c)
                 if mkdir -p $(dirname $disable_file); touch $disable_file ; then
                     notify "will poweroff to avoid poweroff run \n\t\t $pgm -s "
                 fi
                 exit;;
            (-s) rm -f $disable_file;
                 notify $pgm disabled;
                 exit;;
            (-w) warn=1;;
            (-e) error=1;;
            (-h) help;
                 exit;;
            (--) shift; break;;
            (-*) echo "$0: error - unrecognized option $1" 1>&2; help; exit 1;;
            (*)  break;;
        esac
        shift
    done
}

function help() {
    cat <<'EOF'
            -a: eval account=$2; shift;;
            -i: interactive=1;;
            -v: verbose=1;;
            -d: touch $disable_file;;
            -r: rm -f $disable_file;;
            -w: warn=1;;
            -e: error=1;;
            -h: help;;
EOF

}

function warn() {
    if [ $warn ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function verbose() {
    if [ $verbose ] ; then
        notify "$*"
    fi
    logmsg "$*"
}

function notify() {
    if [ -t 1 ] ; then
        echo -e "${pgm}" "$*"
    else
        notify-send "${pgm}" "$*"
    fi
    logmsg "$*"
}

function logmsg() {
    #creating prolem
    logger -i -p local1.notice -t ${pgm}  -- "$*"
}



pgm=$(basename $0)

main $@
